### ISSUE TITLE
Error starting recognition after executing adb command

### ISSUE THREAD

**Issue by chestermeleon** [KieronQuinn/AmbientMusicMod#108]
i followed the guide and i used the adb command, and it worked flawlessly for a couple of days, now does not work when i use the command once again (it finishes succesflly), now  it says that i need root access "Error starting recognittion,Root is required to run recognition on this device ". I'm using a xiaomi redmi note 8 gingko and i have installed lineage 18.1, i on't understand why only worked for some time, i already tried rooting my device but it keeps failing, i already unistalled and reinstalled shizuku and AmbientMusicMod and the issue still persists

**Comment by KieronQuinn** [comment]
The error message you are getting can only mean that Shell does not have the permission to run recognitions. Lineage OS is Android 11, so that is consistent with not having the permission - Shizuku will not help you here.

You need to get root working to use Ambient Music Mod, and I can't help you there.

**Comment by chestermeleon** [comment]
Thank you for the answer, but why it worked only for a couple of days ?

**Comment by KieronQuinn** [comment]
Since you're on Android 11 I assume you had root working without knowing it. Shell doesn't have the permission to work on that version, there's no other explanation.
