### ISSUE TITLE
AMM stops Banking App

### ISSUE THREAD

**Issue by BLACK4585** [KieronQuinn/AmbientMusicMod#254]
Hey,
a few days ago I noticed some weird behaviour regarding my banking app. And since there was a newer version of the custom ROM I'm using available, I clean flashed my device. A few backup restores, clean flashes and tries later, I can now report that AMM stops my banking app from working. Just installing, not ever opening it leads to stopping the app from working and redirecting me to the banks website telling me about an unsave device. I'm using KSU. Without AMM the app works perfectly.
I also tested version 2.3.4 to check if the new update is causing this problem, which is not the case.
It would be nice if somebody else could test this, just install AMM, [the banking app](https://play.google.com/store/apps/details?id=com.starfinanz.smob.android.sfinanzstatus&hl=de) and see, if the app starts into the login screen.

If the described problem occurs to others, I guess the banking app introduced some new checks? The interesting question is, if it's possible to make the app work again, I really like it.

Thank you in advance for the support!

**Comment by KieronQuinn** [comment]
This is due to accessibility service restrictions, there's nothing I can do. It's a dumb decision on the part of the bank.

**Comment by BLACK4585** [comment]
Can you give me a more detailed explanation of this? I'm interested in this, also because I might ask the support about this, why they block a non-root requiring app.

**Comment by KieronQuinn** [comment]
> Can you give me a more detailed explanation of this? I'm interested in this, also because I might ask the support about this, why they block a non-root requiring app.

They're blanket blocking access if the device has a sideloaded app with an accessibility service. If they really want to block non-Play Accessibility Services (which has debatable to zero security impact, depending on the Android version), they should be blocking only if the service is _enabled_.

**Comment by BLACK4585** [comment]
With accessibility service, do you mean the service which e.g. Bitwarden is also using for it's quick settings tile? Or something different? Because I have other apps using the accessibility service (also Bitwarden) but they work perfectly.

**Comment by KieronQuinn** [comment]
It's specifically accessibility services from sideloaded apps, apps not from Google Play. If they blocked them all, they could be in breach of accessibility laws

**Comment by BLACK4585** [comment]
Okay thank you very much for your explanation!

**Comment by KieronQuinn** [comment]
> Hi,I have many sideloaded accesibility apps and root apps and LSPosed modules and whatever and my banking app (Raiffeisen) only complains about this one. And I didn't even enable the accessibly service for it.

There's nothing I can do. It's not possible to fake or spoof the install source to work around this.

**Comment by BLACK4585** [comment]
To release this app via GPlay or FDroid is not a way around?

**Comment by KieronQuinn** [comment]
F-Droid is still sideloading. Google Play would get my account banned.

**Comment by KieronQuinn** [comment]
As a follow up to this, I've been looking at implementing a feature that will use Accessibility Services in [uTag](https://github.com/KieronQuinn/uTag), so have done a bit of investigation into exactly why this is happening for this specific bank, when others only fail checks when the service is _enabled_. Turns out, there's an unfortunate coincidence at play:

- The bank app is using a mobile security SDK of some sort to create a secure environment. The naming of some of the errors in code suggests it _may_ be [OneSpan](https://www.onespan.com/), but I'm not sure. This SDK mentions [using QUERY_ALL_PACKAGES](https://docs.onespan.com/docs/oapps-ig-integrate-app-shielding-on-android-700-701) if available, which means they're likely doing package scanning, which is important in a moment.
- There's two checks at play here: 
  - It's checking if any accessibility services that have been sideloaded are _enabled_. If you enable any sideloaded accessibility service, it will fail to start
  - It's checking for a list of known package names, most likely from some sort of internal list of "red flags"
 - Ambient Music Mod is on that list. It's probably been on it since the days when it was an Xposed-only module, perhaps they built a list of modules during that time and don't remove apps from it.
 - Because AMM uses an accessibility service, it declares a service with the action `android.accessibilityservice.AccessibilityService`, which either this SDK or the developers of the banking app includes in their `queries` block, which makes AMM visible to the banking app, _regardless of if the service is enabled or not_.
 - This means that it's always visible when it's doing the package name list check, and will always fail that.

You can reproduce this very easily by making a skeleton app that declares an accessibility service and whose package name is `com.kieronquinn.app.ambientmusicmod`. Simply having an app installed like that will cause it the bank app to fail to open.

Even disabling the service component doesn't block this detection, the only way to resolve it would be to move the accessibility service out into its own companion app, which would still have the `android.accessibilityservice.AccessibilityService` action, but would only cause the bank app to fail to launch when the service is enabled (since the companion would not have a package name that's on their shitlist). That is, unless the SDK adds it to their list too.

For rooted users, installing the [Hide-My-Applist](https://github.com/Dr-TSNG/Hide-My-Applist) Xposed module, adding the bank app to Magisk hide and setting a blacklist for the banking app in the HMA configuration to hide AMM is enough to get it to launch. For unrooted users, if the use of a companion app in uTag goes well, I may migrate AMM to a similar setup. It would also remove the need to do the "Allow unrestricted settings" shuffle, as a bonus.

**Comment by BLACK4585** [comment]
Thank you for your detailed investigation.
I also discovered Hide my applist and enabled blocking for all my banking apps. With this setup everything works fine for me. 
So this is maybe the easiest solution for users and can be added to a troubleshooting guide or so.

**Comment by gwuen** [comment]
I can largely confirm the behavior you describe for the banking apps developed by Atruvia AG ([VR Banking](https://play.google.com/store/apps/details?id=de.fiduciagad.banking.vr), [VR SecureGo plus](https://play.google.com/store/apps/details?id=de.fiduciagad.securego.vr)) on Android 17:

- The banking apps declare an intent-query for `android.accessibilityservice.AccessibilityService`, which makes AMM visible to them.
- The apps instantly quit and open a [security warning](https://atruvia.de/sicherheitshinweis) when `com.kieronquinn.app.ambientmusicmod` is present.

I could not find the package name in plaintext in the APKs, so the rule is likely hashed, encoded or remotely configured. However, building AMM (and the Now Playing component) myself, I was able to confirm:

- Removing AMM's Accessibility Service declaration: banking apps work.
- Keeping the service, but changing AMM's `applicationId` (e.g., by simply appending a number): banking apps work.

These specific banking apps do _not_ appear to reject sideloaded accessibility services in general. With the `applicationId` changed, they continue to work even when AMM's service is _enabled_.

Considering this is still a [widely reported problem with AMM](https://www.google.com/search?q=%22ambient+music+mod%22+%22banking%22+site%3Areddit.com), I'd really appreciate it if you could take another look at creating a companion app or, if feasible, changing the `applicationId` in a future release.

PS: Thanks for all the work you put into this app so far :)

**Comment by KieronQuinn** [comment]
As I mentioned above, if you grepped for the package name and didn't find it, it's more likely declaring that query and failing for any _sideloaded_ accessibility service. In that case, changing the package name would be fruitless.

**Comment by gwuen** [comment]
> it's more likely declaring that query and failing for any sideloaded accessibility service

That is exactly what I tested: With a changed `applicationId`, the same sideloaded build continued to work with the banking apps even after AMM's Accessibility Service was not only declared, but also _enabled_ in the Android settings. Therefore, at least for these Atruvia apps, this is not a blanket rejection of sideloaded Accessibility Services.

The plaintext search could still fail if the rules use hashes or are encrypted, encoded, or otherwise obfuscated.

**Comment by KieronQuinn** [comment]
I'm still not going through the effort of changing the package name and migrating everyone to a new one for the case of a few banking apps, sorry. A companion app may be a consideration in the future as a far better option since not all apps will be checking against a list.

If you want to patch it to use a different package name, as it sounds like you already have done, that's on you.

**Comment by gwuen** [comment]
Fair enough, I agree that a companion app would be the cleaner solution. I mainly wanted to document the case with these particular banking apps and how their behavior differs.

Thanks for considering the companion app approach for the future. In the meantime, I'll stick with my self-built APKs :)

PS: For anyone wanting to try this themselves: The `applicationId` not only needs to be changed in the [project config](https://github.com/KieronQuinn/AmbientMusicMod/blob/061cc6458f1731108fd2e16605d13e57207dc64f/app/build.gradle#L43), but also in a few places in the [Now Playing](https://github.com/KieronQuinn/NowPlaying) component. Both APKs must then be built with the same signing key.
