### ISSUE TITLE
Lsposed installed instead of Edxposed

### ISSUE THREAD

**Issue by MuhammadBayiz** [KieronQuinn/AmbientMusicMod#30]
Hi i have installed **Lsposed** instead of xposed and in lsposed you have to give permission to the module to certain app in order to effect those apps and i was wondering what app should i give permission to? 
**Ps**: i have given permission to "System Framework" but the module not working

**Comment by KieronQuinn** [comment]
The app gives you a list of apps to enable it for. The instructions are designed for lsposed, so that's not a problem.

The apps are Pixel Ambient Services, System Framework and Android System Intelligence (may also be called Device Personalization Services). If you don't have the last one, that doesn't matter and you can skip it.
