### ISSUE TITLE
InstallerBuildViewModel.kt and InstallerBuildViewModelImpl.kt are missing from source code

### ISSUE THREAD

**Issue by AgentHV** [KieronQuinn/AmbientMusicMod#36]
The classes `com.kieronquinn.app.ambientmusicmod.app.ui.installer.build.InstallerBuildViewModel` and `com.kieronquinn.app.ambientmusicmod.app.ui.installer.build.InstallerBuildViewModelImpl` are mentioned in `AmbientApplication.kt` but the whole ui/installer/build package is missing with them in it. Therefore the app wont build or if outcommenting those the whole Magisk module builder tab is missing.

**Comment by AgentHV** [comment]
Bump


I hate being that guy but until this is resolved fixing any bugs is completely dependent on your personal device choice as no one else will be able to build the app. So this whole open source project is dependent on OnePlus delivering Android 12 for the 7 Pro now...

**Comment by KieronQuinn** [comment]
Done. It was a .gitignore issue, not intentional. 

As for the OnePlus thing, I don't have another non-Pixel device that is running 12. It's hardly my "personal device choice", I don't intentionally choose devices that are slow to be updated - in fact, **the opposite** is why I got the 7TP in the first place, but OnePlus has stopped being fast at updating devices, so there's nothing I can do. 

Debugging Xposed modules to fix things like this via remote logs is incredibly slow and painful. I already know that Android 12 contains significant changes to how sound trigger works (including native support for music recognition apps, which I do **not** intend to support, as the original app does not), so I anticipate it'd be almost impossible to update without having access to a device to work on. 

It took nearly 3 and a half years of work to get this module working in the first place, I'm sure people can wait a bit longer for it to support 12.
