### ISSUE TITLE
Android 12 Support

### ISSUE THREAD

**Issue by KieronQuinn** [KieronQuinn/AmbientMusicMod#38]
Due to changes in Sound Trigger in AOSP Android 12, you may find this module does not work on it.

I do not currently have access to an Android 12 device that is rooted, and is not a Pixel (ie. one this module can be tested on). Once I do, I will attempt to update it to support it.

For more information, see #36 and #37

**Comment by abhinavmarwaha** [comment]
Any update?

**Comment by KieronQuinn** [comment]
Yes, actually. 

I'm working on a total rewrite that will not require Xposed, Magisk (or even root) - at least for the core now playing functionality (the On Demand feature that's on the newer Pixels will require a custom ROM or a Magisk module).

Early stages of development at the moment.

**Comment by KieronQuinn** [comment]
Sneak preview: https://twitter.com/MishaalRahman/status/1534991043950788629

No ETAs just yet, still got a few fairly large hurdles to get over that may take a while, but the core is working.

**Comment by VaughnValle** [comment]
Hi! Can we get access to this preview build? Would love to test this and make it work on my phone.

 I'm using a OP 7T Pro with Pixel Experience Plus ROM running Android 12

**Comment by KieronQuinn** [comment]
No preview builds, they're too much hassle for an unfinished product.

**Comment by Andrew-M3373** [comment]
Thank you so much for the development of this!
I'm not sure if it helps, but I just wanted to report the issues on my end with running the mod on Android 12. 

Device: Google Pixel 2 (walleye) on LineageOS 19.1

Stuff that does work:
- Magisk module installation
- Enabling LSPosed (zygisk) module
- Launching Pixel Ambient Services app and changing settings (unable without Magisk module)

Issues:
- Sound model is marked as incompatible
- No matter what way I change the settings, no songs are ever detected
- Banner at the welcome screen in the mod app shows "Xposed module not enabled" message
- When playing music from any other apps, the audio cuts out for a few seconds about every 3 seconds. I've narrowed this down to an issue with the Magisk module since the audio works normally when everything else is disabled and the Magisk module is the only thing enabled.

Again, I really appreciate your work on this. If there's any testing that I can do to help, logs I can send, or more information you need, I'm more than happy to help. I know you said no preview builds, but I am willing to install any if it would help for testing purposes.

**Comment by KieronQuinn** [comment]
Yes, the issues on Android 12 are known - that's why this issue exists. They will be fixed in the next update, which removes the need for the Xposed module entirely.

**Comment by KieronQuinn** [comment]
Version 2.0 is now released with Android 12 support, amongst many other things.
