### ISSUE TITLE
Doesn't Recognise Songs - Noise during playback

### ISSUE THREAD

**Issue by mdcc22** [KieronQuinn/AmbientMusicMod#47]
I have tried recognising songs manually from the Ambient Music Mod App. I played a song, the app showed no results found. Tried playing the playback and it was full of noise. Tried lowering the gain upto 0.1x and still the noise was there.

I am using Galaxy S20 FE 5G, not rooted. Can give logs if needed.

Thanks for your Awesome work!

**Comment by KieronQuinn** [comment]
Assuming the close was accidental:

Unfortunately there's nothing I can do about this. The noise is coming from the audio sent from the mic, 0.1x gain is an attempted workaround (lower the volume - lower the noise - possibly get some useful audio), since Android doesn't provide any sort of way of controlling the input volume. 

If you've not got any third party audio tweaks installed (including old Ambient Music Mod - uninstall if you do), I can only assume that the assistant mic on your device has a whacking great gain on it to try to compensate for something, making it unusable for music recognition.

**Comment by niklas389** [comment]
My 8T (running Nameless AOSP) doesn't really record anything - and if it's only static with some fractions you can assume may be the music that was playing.
And it does that regardless of the set mic gain

**Comment by Ynng** [comment]
Same thing here, running pixel experience on a Xiaomi 11 (venus)
Static during recording but google assistant, recording and calling works fine.

**Comment by KieronQuinn** [comment]
> Same thing here, running pixel experience on a Xiaomi 11 (venus) Noise peaks most but not all times during recording
> 
> google assistant, recording and calling in other applications works fine.
> 
> This issue should be opened again

This was fixed in 2.0.2, I suggest you update.

**Comment by Ynng** [comment]
Oh sorry, didn't see the setting there.
That indeed resolved the issue.

**Comment by punderino** [comment]
Now it sounds fine but cuts in and out the entire time for me on Android 12.1 EvolutionX for OnePlus 8T

**Comment by KieronQuinn** [comment]
> Now it sounds fine but cuts in and out the entire time for me on Android 12.1 EvolutionX for OnePlus 8T

Cutting in and out really is a microphone issue, or it might alternatively just be physics. Moving closer to the speaker might help.

**Comment by peetereczek** [comment]
@mdcc22 was issue resolved in your case? I observe it on S22 Ultra now

**Comment by KieronQuinn** [comment]
> @mdcc22 was issue resolved in your case? I observe it on S22 Ultra now

Enable the Alternative Encoding option, this has fixed it for everyone else

**Comment by peetereczek** [comment]
> option

True, did and works perfectly 👌🏻 Thank you
