### ISSUE TITLE
Infinite loading & No music recognized

### ISSUE THREAD

**Issue by Ynng** [KieronQuinn/AmbientMusicMod#68]
Clicking the widget to detect music does nothing.
Widget shows “No Music Recognized”, clicking on it opens the now playing history correctly.

Music detection worked before, this just happened.

Will provide logs soon

![11F7180E-7987-46C0-95C4-D06E56285BF4](https://user-images.githubusercontent.com/44907675/175357681-71ff65ef-94aa-4733-8e5f-418ac4d30a13.jpeg)

**Comment by KieronQuinn** [comment]
Reboot, if that doesn't work reinstall. It's stuck in the system.

**Comment by peetereczek** [comment]
It's strange, because application and whole functionality is working, for some time. After few hours Now Playing gets into that state, that we see only infinite loading and no music is being recognized. OnDemand also stops working. I observe het on my both Samsung devices (S22 with OneUI 4.1 and Tab S5e with Lineage OS 19.1)

Maybe we can enable some logging to figura out what's happening in the background?
